### ISSUE TITLE
Registrarの選択画面が汚い

### ISSUE THREAD

**Issue by Chaha1n** [NITTC-ComputerClub/Udon.Client.Nfc#11]
汚いです

**Comment by Chaha1n** [comment]
とりあえず中央ぞろえにしました

**Comment by Chaha1n** [comment]
なんかもうちょっとあると思うので考えとく...
![image](https://user-images.githubusercontent.com/49513840/90847084-acb66e00-e3a4-11ea-9d74-f53db937fbbd.png)

**Comment by siketyan** [comment]
Tailwind とか Bootstrap とかそういうの使っていいよ

**Comment by Chaha1n** [comment]
https://github.com/NITTC-ComputerClub/Udon.Client.Nfc/commit/7b851fcb4876435f0dbc9f34deb67a47d50732d3
のへんで多少マシに
