### ISSUE TITLE
IDmの追加時、なぜか対象のインデックスの次の人にも追加される

### ISSUE THREAD

**Issue by Chaha1n** [NITTC-ComputerClub/Udon.Client.Nfc#13]
ちょっとよくわからないんですけど一枚カードを追加すると２人に追加されます　謎です

**Comment by Chaha1n** [comment]
明日試すこと
cntを定数にして試す

**Comment by siketyan** [comment]
58 行と 62 行に書いてあるのでまあはいという感じです

**Comment by Chaha1n** [comment]
確かに…🙏🙏🙏

**Comment by Chaha1n** [comment]
fixed on https://github.com/NITTC-ComputerClub/Udon.Client.Nfc/commit/c4cd511836834dd1e3b8f1db674dd5e7e773c089
