### ISSUE TITLE
命名規則がバラバラで不明瞭

### ISSUE THREAD

**Issue by Chaha1n** [NITTC-ComputerClub/Udon.Client.Nfc#23]
CardReader.read()とかは他の人が見たときにパッと理解しづらいなーと

**Comment by Chaha1n** [comment]
全体的にマジ命名どうしたらいいか分かりません、パッと思ったのはCardReader.read()→begin_nfc_listening()とか思ったけどそれは長いのか…？とか思ったり…
あとはIDm→member-idの変換をconvert_IDmとするのもバイト配列からのエンコードですか？て感じあるので
直した方がいいと思いました... そもそもPythonのメソッド名がスネークケースで全小文字が推奨らしいし…やっていきます…

**Comment by Chaha1n** [comment]
recordMemberId→record_member_id
tagIDbeforeConvert→idmでよくない？
など…

**Comment by fuu38** [comment]
CardReader.convert_IDm→to_member_id これでしょ(この命名ならIDmが持ってそう感もあるけど…)

**Comment by siketyan** [comment]
まずはモジュール分割

**Comment by fuu38** [comment]
どのへんまで分割すべきですか…？(おすすめの資料などあれば教えてほしいです)

**Comment by siketyan** [comment]
うーん， Python でのベストプラクティスがわからないけどとりあえず WebSocket 部分とカードリーダ部分と members-db とのやりとり部分は分けたほうがよさそう

**Comment by fuu38** [comment]
なるほど
それぞれ別の動作なので、全てCardReaderクラスやそのサブクラスで実装するのは確かに違和感ありますね…
ありがとうございます、練ってみます

**Comment by siketyan** [comment]
クラスを使ってオブジェクト指向してみるのもありだと思う．
これは役割とか仕事を考えると分割しやすい，
さっきコメントした分け方をベースにして，

- クラス名からして適切な役割を担っているか？
- クラス名に適さない仕事をしていないか？
- 仕事を持ちすぎて "神クラス" になっていないか？

あたりをチェックしていくといい感じになると思う！

**Comment by fuu38** [comment]
ありがとうございます！考えてみます

**Comment by fuu38** [comment]
概ね改修が終わりました、
- udon_modulesへモジュール化
- 命名規則の修正
など
あとはちょこちょこ直して動作確認します
