### ISSUE TITLE
新規登録時、部員リストをどうやって受け取るか

### ISSUE THREAD

**Issue by fuu38** [NITTC-ComputerClub/Udon.Client.Nfc#24]
JSが自分で部員リストを取得する必要がありますが、ローカルのファイルを読みこめないぽいのでどうするか
思いついたのは部員リストを供給するAPIを内部で建てるとか

**Comment by siketyan** [comment]
https://github.com/NITTC-ComputerClub/members-db-dist

**Comment by fuu38** [comment]
いわれてみたらその通りですね そうします
