### ISSUE TITLE
新規カード登録時のユーザー指定

### ISSUE THREAD

**Issue by Chaha1n** [NITTC-ComputerClub/Udon.Client.Nfc#7]
どのユーザーに対してカードを登録するかの実装、ユーザーからの入力が必要になるけどラズパイから入力できるのか問題
WebAppでユーザーが今から登録しますってサーバーに連絡しておいて、NFCクライアントは単にIDmを投げたらどのユーザーに紐づけたよ～って返してもらうとか...?

**Comment by siketyan** [comment]
普通にマウスで操作させればよさそう，どのみち GUI 環境は必要なので

**Comment by Chaha1n** [comment]
ｱ
